# -*- coding: utf-8 -*-
"""AgenteHippa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zB2RJN4XDtN528y4rgQeOB89e-ogjVI4
"""

from google.colab import files

print("Selecciona y sube tu archivo hippa.pdf desde tu equipo:")
uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader

# Cargar el archivo subido
loader = PyPDFLoader("hippa.pdf")
docs = loader.load()

print("\n¡Éxito total! Páginas leídas del documento HIPAA:", len(docs))

!pip install -q -U langchain langchain-community langchain-google-genai langchain-text-splitters pypdf

import os
from getpass import getpass

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

# --- 1. API Key ---
if "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] = getpass("Ingresa tu Google API Key:")

# --- 2. Cargar el PDF local ---
PDF_PATH = "hippa.pdf"  # asume que ya lo subiste al entorno local de Colab

loader = PyPDFLoader(PDF_PATH)
docs = loader.load()
print(f"Páginas cargadas: {len(docs)}")

# --- 3. Dividir en chunks ---
splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150,
)
chunks = splitter.split_documents(docs)
print(f"Chunks generados: {len(chunks)}")

# --- 4. Embeddings con el modelo actual de Google ---
embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

# --- 5. Vectorstore en memoria ---
vectorstore = InMemoryVectorStore.from_documents(
    documents=chunks,
    embedding=embeddings,
)
retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

# --- 6. Modelo de chat (alias siempre apunta al flash GA más reciente) ---
llm = ChatGoogleGenerativeAI(
    model="gemini-flash-latest",
    temperature=0.2,
)

# --- 7. Prompt en español ---
prompt = ChatPromptTemplate.from_template(
    """Eres un asistente experto que responde preguntas sobre un documento legal (HIPAA).
El documento fuente está en inglés, pero tú SIEMPRE debes responder en español,
de forma clara, profesional y directa, como si tradujeras y explicaras el contenido
para alguien que no domina el inglés técnico-legal.

Usa únicamente la información del siguiente contexto para responder.
Si la respuesta no está en el contexto, dilo explícitamente en lugar de inventar.

Contexto:
{context}

Pregunta:
{question}

Respuesta en español:"""
)

def format_docs(retrieved_docs):
    return "\n\n".join(d.page_content for d in retrieved_docs)

# --- 8. Cadena RAG con LCEL ---
rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# --- 9. Prueba ---
pregunta = "¿Cuáles son las reglas principales que establece HIPAA sobre la privacidad de la información médica?"
respuesta = rag_chain.invoke(pregunta)
print(respuesta)